site_name: ספייס סאגה - תיעוד

theme:
  name: material
  # custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  language: he
  palette: 
    scheme: slate
    primary: custom
    accent: blue
  font:
    text: IBM Plex Sans Hebrew
  features:
    - navigation.tabs
    - navigation.footer

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets
  - md_in_html

extra_css:
  - stylesheets/extra.css